// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: cv.proto

package grpc.proto;

public interface CurriculumVitaeOrBuilder extends
    // @@protoc_insertion_point(interface_extends:CurriculumVitae)
    com.google.protobuf.MessageOrBuilder {

  /**
   * <code>.Person person = 1;</code>
   * @return Whether the person field is set.
   */
  boolean hasPerson();
  /**
   * <code>.Person person = 1;</code>
   * @return The person.
   */
  grpc.proto.Person getPerson();
  /**
   * <code>.Person person = 1;</code>
   */
  grpc.proto.PersonOrBuilder getPersonOrBuilder();

  /**
   * <code>repeated .Job previousJobs = 2;</code>
   */
  java.util.List<grpc.proto.Job> 
      getPreviousJobsList();
  /**
   * <code>repeated .Job previousJobs = 2;</code>
   */
  grpc.proto.Job getPreviousJobs(int index);
  /**
   * <code>repeated .Job previousJobs = 2;</code>
   */
  int getPreviousJobsCount();
  /**
   * <code>repeated .Job previousJobs = 2;</code>
   */
  java.util.List<? extends grpc.proto.JobOrBuilder> 
      getPreviousJobsOrBuilderList();
  /**
   * <code>repeated .Job previousJobs = 2;</code>
   */
  grpc.proto.JobOrBuilder getPreviousJobsOrBuilder(
      int index);

  /**
   * <code>string description = 3;</code>
   * @return The description.
   */
  java.lang.String getDescription();
  /**
   * <code>string description = 3;</code>
   * @return The bytes for description.
   */
  com.google.protobuf.ByteString
      getDescriptionBytes();
}
