// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: cv.proto

package grpc.proto;

public interface RequestOrBuilder extends
    // @@protoc_insertion_point(interface_extends:Request)
    com.google.protobuf.MessageOrBuilder {

  /**
   * <code>.Request.Action action = 1;</code>
   * @return The enum numeric value on the wire for action.
   */
  int getActionValue();
  /**
   * <code>.Request.Action action = 1;</code>
   * @return The action.
   */
  grpc.proto.Request.Action getAction();

  /**
   * <code>.Country country = 2;</code>
   * @return The enum numeric value on the wire for country.
   */
  int getCountryValue();
  /**
   * <code>.Country country = 2;</code>
   * @return The country.
   */
  grpc.proto.Country getCountry();
}
