// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: cv.proto

package grpc.proto;

public interface BirthOrBuilder extends
    // @@protoc_insertion_point(interface_extends:Birth)
    com.google.protobuf.MessageOrBuilder {

  /**
   * <code>.Country country = 1;</code>
   * @return The enum numeric value on the wire for country.
   */
  int getCountryValue();
  /**
   * <code>.Country country = 1;</code>
   * @return The country.
   */
  grpc.proto.Country getCountry();

  /**
   * <code>string date = 2;</code>
   * @return The date.
   */
  java.lang.String getDate();
  /**
   * <code>string date = 2;</code>
   * @return The bytes for date.
   */
  com.google.protobuf.ByteString
      getDateBytes();
}
