// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: cv.proto

package grpc.proto;

public interface JobOrBuilder extends
    // @@protoc_insertion_point(interface_extends:Job)
    com.google.protobuf.MessageOrBuilder {

  /**
   * <code>string job = 1;</code>
   * @return The job.
   */
  java.lang.String getJob();
  /**
   * <code>string job = 1;</code>
   * @return The bytes for job.
   */
  com.google.protobuf.ByteString
      getJobBytes();

  /**
   * <code>string company = 2;</code>
   * @return The company.
   */
  java.lang.String getCompany();
  /**
   * <code>string company = 2;</code>
   * @return The bytes for company.
   */
  com.google.protobuf.ByteString
      getCompanyBytes();
}
