/**
 * Autogenerated by Thrift Compiler (0.12.0)
 *
 * DO NOT EDIT UNLESS YOU ARE SURE THAT YOU KNOW WHAT YOU ARE DOING
 *  @generated
 */
package rpc.thrift.aircondition;

@SuppressWarnings({"cast", "rawtypes", "serial", "unchecked", "unused"})
@javax.annotation.Generated(value = "Autogenerated by Thrift Compiler (0.12.0)", date = "2020-04-26")
public class AirCondition {

  public interface Iface extends rpc.thrift.shared.BaseDevice.Iface {

    public double changeTemperature(double temperature) throws rpc.thrift.shared.DeviceNotActiveException, InvalidTemperatureException, org.apache.thrift.TException;

  }

  public interface AsyncIface extends rpc.thrift.shared.BaseDevice .AsyncIface {

    public void changeTemperature(double temperature, org.apache.thrift.async.AsyncMethodCallback<java.lang.Double> resultHandler) throws org.apache.thrift.TException;

  }

  public static class Client extends rpc.thrift.shared.BaseDevice.Client implements Iface {
    public static class Factory implements org.apache.thrift.TServiceClientFactory<Client> {
      public Factory() {}
      public Client getClient(org.apache.thrift.protocol.TProtocol prot) {
        return new Client(prot);
      }
      public Client getClient(org.apache.thrift.protocol.TProtocol iprot, org.apache.thrift.protocol.TProtocol oprot) {
        return new Client(iprot, oprot);
      }
    }

    public Client(org.apache.thrift.protocol.TProtocol prot)
    {
      super(prot, prot);
    }

    public Client(org.apache.thrift.protocol.TProtocol iprot, org.apache.thrift.protocol.TProtocol oprot) {
      super(iprot, oprot);
    }

    public double changeTemperature(double temperature) throws rpc.thrift.shared.DeviceNotActiveException, InvalidTemperatureException, org.apache.thrift.TException
    {
      send_changeTemperature(temperature);
      return recv_changeTemperature();
    }

    public void send_changeTemperature(double temperature) throws org.apache.thrift.TException
    {
      changeTemperature_args args = new changeTemperature_args();
      args.setTemperature(temperature);
      sendBase("changeTemperature", args);
    }

    public double recv_changeTemperature() throws rpc.thrift.shared.DeviceNotActiveException, InvalidTemperatureException, org.apache.thrift.TException
    {
      changeTemperature_result result = new changeTemperature_result();
      receiveBase(result, "changeTemperature");
      if (result.isSetSuccess()) {
        return result.success;
      }
      if (result.deviceNotActiveException != null) {
        throw result.deviceNotActiveException;
      }
      if (result.invalidTemperatureException != null) {
        throw result.invalidTemperatureException;
      }
      throw new org.apache.thrift.TApplicationException(org.apache.thrift.TApplicationException.MISSING_RESULT, "changeTemperature failed: unknown result");
    }

  }
  public static class AsyncClient extends rpc.thrift.shared.BaseDevice.AsyncClient implements AsyncIface {
    public static class Factory implements org.apache.thrift.async.TAsyncClientFactory<AsyncClient> {
      private org.apache.thrift.async.TAsyncClientManager clientManager;
      private org.apache.thrift.protocol.TProtocolFactory protocolFactory;
      public Factory(org.apache.thrift.async.TAsyncClientManager clientManager, org.apache.thrift.protocol.TProtocolFactory protocolFactory) {
        this.clientManager = clientManager;
        this.protocolFactory = protocolFactory;
      }
      public AsyncClient getAsyncClient(org.apache.thrift.transport.TNonblockingTransport transport) {
        return new AsyncClient(protocolFactory, clientManager, transport);
      }
    }

    public AsyncClient(org.apache.thrift.protocol.TProtocolFactory protocolFactory, org.apache.thrift.async.TAsyncClientManager clientManager, org.apache.thrift.transport.TNonblockingTransport transport) {
      super(protocolFactory, clientManager, transport);
    }

    public void changeTemperature(double temperature, org.apache.thrift.async.AsyncMethodCallback<java.lang.Double> resultHandler) throws org.apache.thrift.TException {
      checkReady();
      changeTemperature_call method_call = new changeTemperature_call(temperature, resultHandler, this, ___protocolFactory, ___transport);
      this.___currentMethod = method_call;
      ___manager.call(method_call);
    }

    public static class changeTemperature_call extends org.apache.thrift.async.TAsyncMethodCall<java.lang.Double> {
      private double temperature;
      public changeTemperature_call(double temperature, org.apache.thrift.async.AsyncMethodCallback<java.lang.Double> resultHandler, org.apache.thrift.async.TAsyncClient client, org.apache.thrift.protocol.TProtocolFactory protocolFactory, org.apache.thrift.transport.TNonblockingTransport transport) throws org.apache.thrift.TException {
        super(client, protocolFactory, transport, resultHandler, false);
        this.temperature = temperature;
      }

      public void write_args(org.apache.thrift.protocol.TProtocol prot) throws org.apache.thrift.TException {
        prot.writeMessageBegin(new org.apache.thrift.protocol.TMessage("changeTemperature", org.apache.thrift.protocol.TMessageType.CALL, 0));
        changeTemperature_args args = new changeTemperature_args();
        args.setTemperature(temperature);
        args.write(prot);
        prot.writeMessageEnd();
      }

      public java.lang.Double getResult() throws rpc.thrift.shared.DeviceNotActiveException, InvalidTemperatureException, org.apache.thrift.TException {
        if (getState() != org.apache.thrift.async.TAsyncMethodCall.State.RESPONSE_READ) {
          throw new java.lang.IllegalStateException("Method call not finished!");
        }
        org.apache.thrift.transport.TMemoryInputTransport memoryTransport = new org.apache.thrift.transport.TMemoryInputTransport(getFrameBuffer().array());
        org.apache.thrift.protocol.TProtocol prot = client.getProtocolFactory().getProtocol(memoryTransport);
        return (new Client(prot)).recv_changeTemperature();
      }
    }

  }

  public static class Processor<I extends Iface> extends rpc.thrift.shared.BaseDevice.Processor<I> implements org.apache.thrift.TProcessor {
    private static final org.slf4j.Logger _LOGGER = org.slf4j.LoggerFactory.getLogger(Processor.class.getName());
    public Processor(I iface) {
      super(iface, getProcessMap(new java.util.HashMap<java.lang.String, org.apache.thrift.ProcessFunction<I, ? extends org.apache.thrift.TBase>>()));
    }

    protected Processor(I iface, java.util.Map<java.lang.String, org.apache.thrift.ProcessFunction<I, ? extends org.apache.thrift.TBase>> processMap) {
      super(iface, getProcessMap(processMap));
    }

    private static <I extends Iface> java.util.Map<java.lang.String,  org.apache.thrift.ProcessFunction<I, ? extends org.apache.thrift.TBase>> getProcessMap(java.util.Map<java.lang.String, org.apache.thrift.ProcessFunction<I, ? extends  org.apache.thrift.TBase>> processMap) {
      processMap.put("changeTemperature", new changeTemperature());
      return processMap;
    }

    public static class changeTemperature<I extends Iface> extends org.apache.thrift.ProcessFunction<I, changeTemperature_args> {
      public changeTemperature() {
        super("changeTemperature");
      }

      public changeTemperature_args getEmptyArgsInstance() {
        return new changeTemperature_args();
      }

      protected boolean isOneway() {
        return false;
      }

      @Override
      protected boolean rethrowUnhandledExceptions() {
        return false;
      }

      public changeTemperature_result getResult(I iface, changeTemperature_args args) throws org.apache.thrift.TException {
        changeTemperature_result result = new changeTemperature_result();
        try {
          result.success = iface.changeTemperature(args.temperature);
          result.setSuccessIsSet(true);
        } catch (rpc.thrift.shared.DeviceNotActiveException deviceNotActiveException) {
          result.deviceNotActiveException = deviceNotActiveException;
        } catch (InvalidTemperatureException invalidTemperatureException) {
          result.invalidTemperatureException = invalidTemperatureException;
        }
        return result;
      }
    }

  }

  public static class AsyncProcessor<I extends AsyncIface> extends rpc.thrift.shared.BaseDevice.AsyncProcessor<I> {
    private static final org.slf4j.Logger _LOGGER = org.slf4j.LoggerFactory.getLogger(AsyncProcessor.class.getName());
    public AsyncProcessor(I iface) {
      super(iface, getProcessMap(new java.util.HashMap<java.lang.String, org.apache.thrift.AsyncProcessFunction<I, ? extends org.apache.thrift.TBase, ?>>()));
    }

    protected AsyncProcessor(I iface, java.util.Map<java.lang.String,  org.apache.thrift.AsyncProcessFunction<I, ? extends  org.apache.thrift.TBase, ?>> processMap) {
      super(iface, getProcessMap(processMap));
    }

    private static <I extends AsyncIface> java.util.Map<java.lang.String,  org.apache.thrift.AsyncProcessFunction<I, ? extends  org.apache.thrift.TBase,?>> getProcessMap(java.util.Map<java.lang.String,  org.apache.thrift.AsyncProcessFunction<I, ? extends  org.apache.thrift.TBase, ?>> processMap) {
      processMap.put("changeTemperature", new changeTemperature());
      return processMap;
    }

    public static class changeTemperature<I extends AsyncIface> extends org.apache.thrift.AsyncProcessFunction<I, changeTemperature_args, java.lang.Double> {
      public changeTemperature() {
        super("changeTemperature");
      }

      public changeTemperature_args getEmptyArgsInstance() {
        return new changeTemperature_args();
      }

      public org.apache.thrift.async.AsyncMethodCallback<java.lang.Double> getResultHandler(final org.apache.thrift.server.AbstractNonblockingServer.AsyncFrameBuffer fb, final int seqid) {
        final org.apache.thrift.AsyncProcessFunction fcall = this;
        return new org.apache.thrift.async.AsyncMethodCallback<java.lang.Double>() { 
          public void onComplete(java.lang.Double o) {
            changeTemperature_result result = new changeTemperature_result();
            result.success = o;
            result.setSuccessIsSet(true);
            try {
              fcall.sendResponse(fb, result, org.apache.thrift.protocol.TMessageType.REPLY,seqid);
            } catch (org.apache.thrift.transport.TTransportException e) {
              _LOGGER.error("TTransportException writing to internal frame buffer", e);
              fb.close();
            } catch (java.lang.Exception e) {
              _LOGGER.error("Exception writing to internal frame buffer", e);
              onError(e);
            }
          }
          public void onError(java.lang.Exception e) {
            byte msgType = org.apache.thrift.protocol.TMessageType.REPLY;
            org.apache.thrift.TSerializable msg;
            changeTemperature_result result = new changeTemperature_result();
            if (e instanceof rpc.thrift.shared.DeviceNotActiveException) {
              result.deviceNotActiveException = (rpc.thrift.shared.DeviceNotActiveException) e;
              result.setDeviceNotActiveExceptionIsSet(true);
              msg = result;
            } else if (e instanceof InvalidTemperatureException) {
              result.invalidTemperatureException = (InvalidTemperatureException) e;
              result.setInvalidTemperatureExceptionIsSet(true);
              msg = result;
            } else if (e instanceof org.apache.thrift.transport.TTransportException) {
              _LOGGER.error("TTransportException inside handler", e);
              fb.close();
              return;
            } else if (e instanceof org.apache.thrift.TApplicationException) {
              _LOGGER.error("TApplicationException inside handler", e);
              msgType = org.apache.thrift.protocol.TMessageType.EXCEPTION;
              msg = (org.apache.thrift.TApplicationException)e;
            } else {
              _LOGGER.error("Exception inside handler", e);
              msgType = org.apache.thrift.protocol.TMessageType.EXCEPTION;
              msg = new org.apache.thrift.TApplicationException(org.apache.thrift.TApplicationException.INTERNAL_ERROR, e.getMessage());
            }
            try {
              fcall.sendResponse(fb,msg,msgType,seqid);
            } catch (java.lang.Exception ex) {
              _LOGGER.error("Exception writing to internal frame buffer", ex);
              fb.close();
            }
          }
        };
      }

      protected boolean isOneway() {
        return false;
      }

      public void start(I iface, changeTemperature_args args, org.apache.thrift.async.AsyncMethodCallback<java.lang.Double> resultHandler) throws org.apache.thrift.TException {
        iface.changeTemperature(args.temperature,resultHandler);
      }
    }

  }

  public static class changeTemperature_args implements org.apache.thrift.TBase<changeTemperature_args, changeTemperature_args._Fields>, java.io.Serializable, Cloneable, Comparable<changeTemperature_args>   {
    private static final org.apache.thrift.protocol.TStruct STRUCT_DESC = new org.apache.thrift.protocol.TStruct("changeTemperature_args");

    private static final org.apache.thrift.protocol.TField TEMPERATURE_FIELD_DESC = new org.apache.thrift.protocol.TField("temperature", org.apache.thrift.protocol.TType.DOUBLE, (short)1);

    private static final org.apache.thrift.scheme.SchemeFactory STANDARD_SCHEME_FACTORY = new changeTemperature_argsStandardSchemeFactory();
    private static final org.apache.thrift.scheme.SchemeFactory TUPLE_SCHEME_FACTORY = new changeTemperature_argsTupleSchemeFactory();

    public double temperature; // required

    /** The set of fields this struct contains, along with convenience methods for finding and manipulating them. */
    public enum _Fields implements org.apache.thrift.TFieldIdEnum {
      TEMPERATURE((short)1, "temperature");

      private static final java.util.Map<java.lang.String, _Fields> byName = new java.util.HashMap<java.lang.String, _Fields>();

      static {
        for (_Fields field : java.util.EnumSet.allOf(_Fields.class)) {
          byName.put(field.getFieldName(), field);
        }
      }

      /**
       * Find the _Fields constant that matches fieldId, or null if its not found.
       */
      @org.apache.thrift.annotation.Nullable
      public static _Fields findByThriftId(int fieldId) {
        switch(fieldId) {
          case 1: // TEMPERATURE
            return TEMPERATURE;
          default:
            return null;
        }
      }

      /**
       * Find the _Fields constant that matches fieldId, throwing an exception
       * if it is not found.
       */
      public static _Fields findByThriftIdOrThrow(int fieldId) {
        _Fields fields = findByThriftId(fieldId);
        if (fields == null) throw new java.lang.IllegalArgumentException("Field " + fieldId + " doesn't exist!");
        return fields;
      }

      /**
       * Find the _Fields constant that matches name, or null if its not found.
       */
      @org.apache.thrift.annotation.Nullable
      public static _Fields findByName(java.lang.String name) {
        return byName.get(name);
      }

      private final short _thriftId;
      private final java.lang.String _fieldName;

      _Fields(short thriftId, java.lang.String fieldName) {
        _thriftId = thriftId;
        _fieldName = fieldName;
      }

      public short getThriftFieldId() {
        return _thriftId;
      }

      public java.lang.String getFieldName() {
        return _fieldName;
      }
    }

    // isset id assignments
    private static final int __TEMPERATURE_ISSET_ID = 0;
    private byte __isset_bitfield = 0;
    public static final java.util.Map<_Fields, org.apache.thrift.meta_data.FieldMetaData> metaDataMap;
    static {
      java.util.Map<_Fields, org.apache.thrift.meta_data.FieldMetaData> tmpMap = new java.util.EnumMap<_Fields, org.apache.thrift.meta_data.FieldMetaData>(_Fields.class);
      tmpMap.put(_Fields.TEMPERATURE, new org.apache.thrift.meta_data.FieldMetaData("temperature", org.apache.thrift.TFieldRequirementType.DEFAULT, 
          new org.apache.thrift.meta_data.FieldValueMetaData(org.apache.thrift.protocol.TType.DOUBLE)));
      metaDataMap = java.util.Collections.unmodifiableMap(tmpMap);
      org.apache.thrift.meta_data.FieldMetaData.addStructMetaDataMap(changeTemperature_args.class, metaDataMap);
    }

    public changeTemperature_args() {
    }

    public changeTemperature_args(
      double temperature)
    {
      this();
      this.temperature = temperature;
      setTemperatureIsSet(true);
    }

    /**
     * Performs a deep copy on <i>other</i>.
     */
    public changeTemperature_args(changeTemperature_args other) {
      __isset_bitfield = other.__isset_bitfield;
      this.temperature = other.temperature;
    }

    public changeTemperature_args deepCopy() {
      return new changeTemperature_args(this);
    }

    @Override
    public void clear() {
      setTemperatureIsSet(false);
      this.temperature = 0.0;
    }

    public double getTemperature() {
      return this.temperature;
    }

    public changeTemperature_args setTemperature(double temperature) {
      this.temperature = temperature;
      setTemperatureIsSet(true);
      return this;
    }

    public void unsetTemperature() {
      __isset_bitfield = org.apache.thrift.EncodingUtils.clearBit(__isset_bitfield, __TEMPERATURE_ISSET_ID);
    }

    /** Returns true if field temperature is set (has been assigned a value) and false otherwise */
    public boolean isSetTemperature() {
      return org.apache.thrift.EncodingUtils.testBit(__isset_bitfield, __TEMPERATURE_ISSET_ID);
    }

    public void setTemperatureIsSet(boolean value) {
      __isset_bitfield = org.apache.thrift.EncodingUtils.setBit(__isset_bitfield, __TEMPERATURE_ISSET_ID, value);
    }

    public void setFieldValue(_Fields field, @org.apache.thrift.annotation.Nullable java.lang.Object value) {
      switch (field) {
      case TEMPERATURE:
        if (value == null) {
          unsetTemperature();
        } else {
          setTemperature((java.lang.Double)value);
        }
        break;

      }
    }

    @org.apache.thrift.annotation.Nullable
    public java.lang.Object getFieldValue(_Fields field) {
      switch (field) {
      case TEMPERATURE:
        return getTemperature();

      }
      throw new java.lang.IllegalStateException();
    }

    /** Returns true if field corresponding to fieldID is set (has been assigned a value) and false otherwise */
    public boolean isSet(_Fields field) {
      if (field == null) {
        throw new java.lang.IllegalArgumentException();
      }

      switch (field) {
      case TEMPERATURE:
        return isSetTemperature();
      }
      throw new java.lang.IllegalStateException();
    }

    @Override
    public boolean equals(java.lang.Object that) {
      if (that == null)
        return false;
      if (that instanceof changeTemperature_args)
        return this.equals((changeTemperature_args)that);
      return false;
    }

    public boolean equals(changeTemperature_args that) {
      if (that == null)
        return false;
      if (this == that)
        return true;

      boolean this_present_temperature = true;
      boolean that_present_temperature = true;
      if (this_present_temperature || that_present_temperature) {
        if (!(this_present_temperature && that_present_temperature))
          return false;
        if (this.temperature != that.temperature)
          return false;
      }

      return true;
    }

    @Override
    public int hashCode() {
      int hashCode = 1;

      hashCode = hashCode * 8191 + org.apache.thrift.TBaseHelper.hashCode(temperature);

      return hashCode;
    }

    @Override
    public int compareTo(changeTemperature_args other) {
      if (!getClass().equals(other.getClass())) {
        return getClass().getName().compareTo(other.getClass().getName());
      }

      int lastComparison = 0;

      lastComparison = java.lang.Boolean.valueOf(isSetTemperature()).compareTo(other.isSetTemperature());
      if (lastComparison != 0) {
        return lastComparison;
      }
      if (isSetTemperature()) {
        lastComparison = org.apache.thrift.TBaseHelper.compareTo(this.temperature, other.temperature);
        if (lastComparison != 0) {
          return lastComparison;
        }
      }
      return 0;
    }

    @org.apache.thrift.annotation.Nullable
    public _Fields fieldForId(int fieldId) {
      return _Fields.findByThriftId(fieldId);
    }

    public void read(org.apache.thrift.protocol.TProtocol iprot) throws org.apache.thrift.TException {
      scheme(iprot).read(iprot, this);
    }

    public void write(org.apache.thrift.protocol.TProtocol oprot) throws org.apache.thrift.TException {
      scheme(oprot).write(oprot, this);
    }

    @Override
    public java.lang.String toString() {
      java.lang.StringBuilder sb = new java.lang.StringBuilder("changeTemperature_args(");
      boolean first = true;

      sb.append("temperature:");
      sb.append(this.temperature);
      first = false;
      sb.append(")");
      return sb.toString();
    }

    public void validate() throws org.apache.thrift.TException {
      // check for required fields
      // check for sub-struct validity
    }

    private void writeObject(java.io.ObjectOutputStream out) throws java.io.IOException {
      try {
        write(new org.apache.thrift.protocol.TCompactProtocol(new org.apache.thrift.transport.TIOStreamTransport(out)));
      } catch (org.apache.thrift.TException te) {
        throw new java.io.IOException(te);
      }
    }

    private void readObject(java.io.ObjectInputStream in) throws java.io.IOException, java.lang.ClassNotFoundException {
      try {
        // it doesn't seem like you should have to do this, but java serialization is wacky, and doesn't call the default constructor.
        __isset_bitfield = 0;
        read(new org.apache.thrift.protocol.TCompactProtocol(new org.apache.thrift.transport.TIOStreamTransport(in)));
      } catch (org.apache.thrift.TException te) {
        throw new java.io.IOException(te);
      }
    }

    private static class changeTemperature_argsStandardSchemeFactory implements org.apache.thrift.scheme.SchemeFactory {
      public changeTemperature_argsStandardScheme getScheme() {
        return new changeTemperature_argsStandardScheme();
      }
    }

    private static class changeTemperature_argsStandardScheme extends org.apache.thrift.scheme.StandardScheme<changeTemperature_args> {

      public void read(org.apache.thrift.protocol.TProtocol iprot, changeTemperature_args struct) throws org.apache.thrift.TException {
        org.apache.thrift.protocol.TField schemeField;
        iprot.readStructBegin();
        while (true)
        {
          schemeField = iprot.readFieldBegin();
          if (schemeField.type == org.apache.thrift.protocol.TType.STOP) { 
            break;
          }
          switch (schemeField.id) {
            case 1: // TEMPERATURE
              if (schemeField.type == org.apache.thrift.protocol.TType.DOUBLE) {
                struct.temperature = iprot.readDouble();
                struct.setTemperatureIsSet(true);
              } else { 
                org.apache.thrift.protocol.TProtocolUtil.skip(iprot, schemeField.type);
              }
              break;
            default:
              org.apache.thrift.protocol.TProtocolUtil.skip(iprot, schemeField.type);
          }
          iprot.readFieldEnd();
        }
        iprot.readStructEnd();

        // check for required fields of primitive type, which can't be checked in the validate method
        struct.validate();
      }

      public void write(org.apache.thrift.protocol.TProtocol oprot, changeTemperature_args struct) throws org.apache.thrift.TException {
        struct.validate();

        oprot.writeStructBegin(STRUCT_DESC);
        oprot.writeFieldBegin(TEMPERATURE_FIELD_DESC);
        oprot.writeDouble(struct.temperature);
        oprot.writeFieldEnd();
        oprot.writeFieldStop();
        oprot.writeStructEnd();
      }

    }

    private static class changeTemperature_argsTupleSchemeFactory implements org.apache.thrift.scheme.SchemeFactory {
      public changeTemperature_argsTupleScheme getScheme() {
        return new changeTemperature_argsTupleScheme();
      }
    }

    private static class changeTemperature_argsTupleScheme extends org.apache.thrift.scheme.TupleScheme<changeTemperature_args> {

      @Override
      public void write(org.apache.thrift.protocol.TProtocol prot, changeTemperature_args struct) throws org.apache.thrift.TException {
        org.apache.thrift.protocol.TTupleProtocol oprot = (org.apache.thrift.protocol.TTupleProtocol) prot;
        java.util.BitSet optionals = new java.util.BitSet();
        if (struct.isSetTemperature()) {
          optionals.set(0);
        }
        oprot.writeBitSet(optionals, 1);
        if (struct.isSetTemperature()) {
          oprot.writeDouble(struct.temperature);
        }
      }

      @Override
      public void read(org.apache.thrift.protocol.TProtocol prot, changeTemperature_args struct) throws org.apache.thrift.TException {
        org.apache.thrift.protocol.TTupleProtocol iprot = (org.apache.thrift.protocol.TTupleProtocol) prot;
        java.util.BitSet incoming = iprot.readBitSet(1);
        if (incoming.get(0)) {
          struct.temperature = iprot.readDouble();
          struct.setTemperatureIsSet(true);
        }
      }
    }

    private static <S extends org.apache.thrift.scheme.IScheme> S scheme(org.apache.thrift.protocol.TProtocol proto) {
      return (org.apache.thrift.scheme.StandardScheme.class.equals(proto.getScheme()) ? STANDARD_SCHEME_FACTORY : TUPLE_SCHEME_FACTORY).getScheme();
    }
  }

  public static class changeTemperature_result implements org.apache.thrift.TBase<changeTemperature_result, changeTemperature_result._Fields>, java.io.Serializable, Cloneable, Comparable<changeTemperature_result>   {
    private static final org.apache.thrift.protocol.TStruct STRUCT_DESC = new org.apache.thrift.protocol.TStruct("changeTemperature_result");

    private static final org.apache.thrift.protocol.TField SUCCESS_FIELD_DESC = new org.apache.thrift.protocol.TField("success", org.apache.thrift.protocol.TType.DOUBLE, (short)0);
    private static final org.apache.thrift.protocol.TField DEVICE_NOT_ACTIVE_EXCEPTION_FIELD_DESC = new org.apache.thrift.protocol.TField("deviceNotActiveException", org.apache.thrift.protocol.TType.STRUCT, (short)1);
    private static final org.apache.thrift.protocol.TField INVALID_TEMPERATURE_EXCEPTION_FIELD_DESC = new org.apache.thrift.protocol.TField("invalidTemperatureException", org.apache.thrift.protocol.TType.STRUCT, (short)2);

    private static final org.apache.thrift.scheme.SchemeFactory STANDARD_SCHEME_FACTORY = new changeTemperature_resultStandardSchemeFactory();
    private static final org.apache.thrift.scheme.SchemeFactory TUPLE_SCHEME_FACTORY = new changeTemperature_resultTupleSchemeFactory();

    public double success; // required
    public @org.apache.thrift.annotation.Nullable rpc.thrift.shared.DeviceNotActiveException deviceNotActiveException; // required
    public @org.apache.thrift.annotation.Nullable InvalidTemperatureException invalidTemperatureException; // required

    /** The set of fields this struct contains, along with convenience methods for finding and manipulating them. */
    public enum _Fields implements org.apache.thrift.TFieldIdEnum {
      SUCCESS((short)0, "success"),
      DEVICE_NOT_ACTIVE_EXCEPTION((short)1, "deviceNotActiveException"),
      INVALID_TEMPERATURE_EXCEPTION((short)2, "invalidTemperatureException");

      private static final java.util.Map<java.lang.String, _Fields> byName = new java.util.HashMap<java.lang.String, _Fields>();

      static {
        for (_Fields field : java.util.EnumSet.allOf(_Fields.class)) {
          byName.put(field.getFieldName(), field);
        }
      }

      /**
       * Find the _Fields constant that matches fieldId, or null if its not found.
       */
      @org.apache.thrift.annotation.Nullable
      public static _Fields findByThriftId(int fieldId) {
        switch(fieldId) {
          case 0: // SUCCESS
            return SUCCESS;
          case 1: // DEVICE_NOT_ACTIVE_EXCEPTION
            return DEVICE_NOT_ACTIVE_EXCEPTION;
          case 2: // INVALID_TEMPERATURE_EXCEPTION
            return INVALID_TEMPERATURE_EXCEPTION;
          default:
            return null;
        }
      }

      /**
       * Find the _Fields constant that matches fieldId, throwing an exception
       * if it is not found.
       */
      public static _Fields findByThriftIdOrThrow(int fieldId) {
        _Fields fields = findByThriftId(fieldId);
        if (fields == null) throw new java.lang.IllegalArgumentException("Field " + fieldId + " doesn't exist!");
        return fields;
      }

      /**
       * Find the _Fields constant that matches name, or null if its not found.
       */
      @org.apache.thrift.annotation.Nullable
      public static _Fields findByName(java.lang.String name) {
        return byName.get(name);
      }

      private final short _thriftId;
      private final java.lang.String _fieldName;

      _Fields(short thriftId, java.lang.String fieldName) {
        _thriftId = thriftId;
        _fieldName = fieldName;
      }

      public short getThriftFieldId() {
        return _thriftId;
      }

      public java.lang.String getFieldName() {
        return _fieldName;
      }
    }

    // isset id assignments
    private static final int __SUCCESS_ISSET_ID = 0;
    private byte __isset_bitfield = 0;
    public static final java.util.Map<_Fields, org.apache.thrift.meta_data.FieldMetaData> metaDataMap;
    static {
      java.util.Map<_Fields, org.apache.thrift.meta_data.FieldMetaData> tmpMap = new java.util.EnumMap<_Fields, org.apache.thrift.meta_data.FieldMetaData>(_Fields.class);
      tmpMap.put(_Fields.SUCCESS, new org.apache.thrift.meta_data.FieldMetaData("success", org.apache.thrift.TFieldRequirementType.DEFAULT, 
          new org.apache.thrift.meta_data.FieldValueMetaData(org.apache.thrift.protocol.TType.DOUBLE)));
      tmpMap.put(_Fields.DEVICE_NOT_ACTIVE_EXCEPTION, new org.apache.thrift.meta_data.FieldMetaData("deviceNotActiveException", org.apache.thrift.TFieldRequirementType.DEFAULT, 
          new org.apache.thrift.meta_data.StructMetaData(org.apache.thrift.protocol.TType.STRUCT, rpc.thrift.shared.DeviceNotActiveException.class)));
      tmpMap.put(_Fields.INVALID_TEMPERATURE_EXCEPTION, new org.apache.thrift.meta_data.FieldMetaData("invalidTemperatureException", org.apache.thrift.TFieldRequirementType.DEFAULT, 
          new org.apache.thrift.meta_data.StructMetaData(org.apache.thrift.protocol.TType.STRUCT, InvalidTemperatureException.class)));
      metaDataMap = java.util.Collections.unmodifiableMap(tmpMap);
      org.apache.thrift.meta_data.FieldMetaData.addStructMetaDataMap(changeTemperature_result.class, metaDataMap);
    }

    public changeTemperature_result() {
    }

    public changeTemperature_result(
      double success,
      rpc.thrift.shared.DeviceNotActiveException deviceNotActiveException,
      InvalidTemperatureException invalidTemperatureException)
    {
      this();
      this.success = success;
      setSuccessIsSet(true);
      this.deviceNotActiveException = deviceNotActiveException;
      this.invalidTemperatureException = invalidTemperatureException;
    }

    /**
     * Performs a deep copy on <i>other</i>.
     */
    public changeTemperature_result(changeTemperature_result other) {
      __isset_bitfield = other.__isset_bitfield;
      this.success = other.success;
      if (other.isSetDeviceNotActiveException()) {
        this.deviceNotActiveException = new rpc.thrift.shared.DeviceNotActiveException(other.deviceNotActiveException);
      }
      if (other.isSetInvalidTemperatureException()) {
        this.invalidTemperatureException = new InvalidTemperatureException(other.invalidTemperatureException);
      }
    }

    public changeTemperature_result deepCopy() {
      return new changeTemperature_result(this);
    }

    @Override
    public void clear() {
      setSuccessIsSet(false);
      this.success = 0.0;
      this.deviceNotActiveException = null;
      this.invalidTemperatureException = null;
    }

    public double getSuccess() {
      return this.success;
    }

    public changeTemperature_result setSuccess(double success) {
      this.success = success;
      setSuccessIsSet(true);
      return this;
    }

    public void unsetSuccess() {
      __isset_bitfield = org.apache.thrift.EncodingUtils.clearBit(__isset_bitfield, __SUCCESS_ISSET_ID);
    }

    /** Returns true if field success is set (has been assigned a value) and false otherwise */
    public boolean isSetSuccess() {
      return org.apache.thrift.EncodingUtils.testBit(__isset_bitfield, __SUCCESS_ISSET_ID);
    }

    public void setSuccessIsSet(boolean value) {
      __isset_bitfield = org.apache.thrift.EncodingUtils.setBit(__isset_bitfield, __SUCCESS_ISSET_ID, value);
    }

    @org.apache.thrift.annotation.Nullable
    public rpc.thrift.shared.DeviceNotActiveException getDeviceNotActiveException() {
      return this.deviceNotActiveException;
    }

    public changeTemperature_result setDeviceNotActiveException(@org.apache.thrift.annotation.Nullable rpc.thrift.shared.DeviceNotActiveException deviceNotActiveException) {
      this.deviceNotActiveException = deviceNotActiveException;
      return this;
    }

    public void unsetDeviceNotActiveException() {
      this.deviceNotActiveException = null;
    }

    /** Returns true if field deviceNotActiveException is set (has been assigned a value) and false otherwise */
    public boolean isSetDeviceNotActiveException() {
      return this.deviceNotActiveException != null;
    }

    public void setDeviceNotActiveExceptionIsSet(boolean value) {
      if (!value) {
        this.deviceNotActiveException = null;
      }
    }

    @org.apache.thrift.annotation.Nullable
    public InvalidTemperatureException getInvalidTemperatureException() {
      return this.invalidTemperatureException;
    }

    public changeTemperature_result setInvalidTemperatureException(@org.apache.thrift.annotation.Nullable InvalidTemperatureException invalidTemperatureException) {
      this.invalidTemperatureException = invalidTemperatureException;
      return this;
    }

    public void unsetInvalidTemperatureException() {
      this.invalidTemperatureException = null;
    }

    /** Returns true if field invalidTemperatureException is set (has been assigned a value) and false otherwise */
    public boolean isSetInvalidTemperatureException() {
      return this.invalidTemperatureException != null;
    }

    public void setInvalidTemperatureExceptionIsSet(boolean value) {
      if (!value) {
        this.invalidTemperatureException = null;
      }
    }

    public void setFieldValue(_Fields field, @org.apache.thrift.annotation.Nullable java.lang.Object value) {
      switch (field) {
      case SUCCESS:
        if (value == null) {
          unsetSuccess();
        } else {
          setSuccess((java.lang.Double)value);
        }
        break;

      case DEVICE_NOT_ACTIVE_EXCEPTION:
        if (value == null) {
          unsetDeviceNotActiveException();
        } else {
          setDeviceNotActiveException((rpc.thrift.shared.DeviceNotActiveException)value);
        }
        break;

      case INVALID_TEMPERATURE_EXCEPTION:
        if (value == null) {
          unsetInvalidTemperatureException();
        } else {
          setInvalidTemperatureException((InvalidTemperatureException)value);
        }
        break;

      }
    }

    @org.apache.thrift.annotation.Nullable
    public java.lang.Object getFieldValue(_Fields field) {
      switch (field) {
      case SUCCESS:
        return getSuccess();

      case DEVICE_NOT_ACTIVE_EXCEPTION:
        return getDeviceNotActiveException();

      case INVALID_TEMPERATURE_EXCEPTION:
        return getInvalidTemperatureException();

      }
      throw new java.lang.IllegalStateException();
    }

    /** Returns true if field corresponding to fieldID is set (has been assigned a value) and false otherwise */
    public boolean isSet(_Fields field) {
      if (field == null) {
        throw new java.lang.IllegalArgumentException();
      }

      switch (field) {
      case SUCCESS:
        return isSetSuccess();
      case DEVICE_NOT_ACTIVE_EXCEPTION:
        return isSetDeviceNotActiveException();
      case INVALID_TEMPERATURE_EXCEPTION:
        return isSetInvalidTemperatureException();
      }
      throw new java.lang.IllegalStateException();
    }

    @Override
    public boolean equals(java.lang.Object that) {
      if (that == null)
        return false;
      if (that instanceof changeTemperature_result)
        return this.equals((changeTemperature_result)that);
      return false;
    }

    public boolean equals(changeTemperature_result that) {
      if (that == null)
        return false;
      if (this == that)
        return true;

      boolean this_present_success = true;
      boolean that_present_success = true;
      if (this_present_success || that_present_success) {
        if (!(this_present_success && that_present_success))
          return false;
        if (this.success != that.success)
          return false;
      }

      boolean this_present_deviceNotActiveException = true && this.isSetDeviceNotActiveException();
      boolean that_present_deviceNotActiveException = true && that.isSetDeviceNotActiveException();
      if (this_present_deviceNotActiveException || that_present_deviceNotActiveException) {
        if (!(this_present_deviceNotActiveException && that_present_deviceNotActiveException))
          return false;
        if (!this.deviceNotActiveException.equals(that.deviceNotActiveException))
          return false;
      }

      boolean this_present_invalidTemperatureException = true && this.isSetInvalidTemperatureException();
      boolean that_present_invalidTemperatureException = true && that.isSetInvalidTemperatureException();
      if (this_present_invalidTemperatureException || that_present_invalidTemperatureException) {
        if (!(this_present_invalidTemperatureException && that_present_invalidTemperatureException))
          return false;
        if (!this.invalidTemperatureException.equals(that.invalidTemperatureException))
          return false;
      }

      return true;
    }

    @Override
    public int hashCode() {
      int hashCode = 1;

      hashCode = hashCode * 8191 + org.apache.thrift.TBaseHelper.hashCode(success);

      hashCode = hashCode * 8191 + ((isSetDeviceNotActiveException()) ? 131071 : 524287);
      if (isSetDeviceNotActiveException())
        hashCode = hashCode * 8191 + deviceNotActiveException.hashCode();

      hashCode = hashCode * 8191 + ((isSetInvalidTemperatureException()) ? 131071 : 524287);
      if (isSetInvalidTemperatureException())
        hashCode = hashCode * 8191 + invalidTemperatureException.hashCode();

      return hashCode;
    }

    @Override
    public int compareTo(changeTemperature_result other) {
      if (!getClass().equals(other.getClass())) {
        return getClass().getName().compareTo(other.getClass().getName());
      }

      int lastComparison = 0;

      lastComparison = java.lang.Boolean.valueOf(isSetSuccess()).compareTo(other.isSetSuccess());
      if (lastComparison != 0) {
        return lastComparison;
      }
      if (isSetSuccess()) {
        lastComparison = org.apache.thrift.TBaseHelper.compareTo(this.success, other.success);
        if (lastComparison != 0) {
          return lastComparison;
        }
      }
      lastComparison = java.lang.Boolean.valueOf(isSetDeviceNotActiveException()).compareTo(other.isSetDeviceNotActiveException());
      if (lastComparison != 0) {
        return lastComparison;
      }
      if (isSetDeviceNotActiveException()) {
        lastComparison = org.apache.thrift.TBaseHelper.compareTo(this.deviceNotActiveException, other.deviceNotActiveException);
        if (lastComparison != 0) {
          return lastComparison;
        }
      }
      lastComparison = java.lang.Boolean.valueOf(isSetInvalidTemperatureException()).compareTo(other.isSetInvalidTemperatureException());
      if (lastComparison != 0) {
        return lastComparison;
      }
      if (isSetInvalidTemperatureException()) {
        lastComparison = org.apache.thrift.TBaseHelper.compareTo(this.invalidTemperatureException, other.invalidTemperatureException);
        if (lastComparison != 0) {
          return lastComparison;
        }
      }
      return 0;
    }

    @org.apache.thrift.annotation.Nullable
    public _Fields fieldForId(int fieldId) {
      return _Fields.findByThriftId(fieldId);
    }

    public void read(org.apache.thrift.protocol.TProtocol iprot) throws org.apache.thrift.TException {
      scheme(iprot).read(iprot, this);
    }

    public void write(org.apache.thrift.protocol.TProtocol oprot) throws org.apache.thrift.TException {
      scheme(oprot).write(oprot, this);
      }

    @Override
    public java.lang.String toString() {
      java.lang.StringBuilder sb = new java.lang.StringBuilder("changeTemperature_result(");
      boolean first = true;

      sb.append("success:");
      sb.append(this.success);
      first = false;
      if (!first) sb.append(", ");
      sb.append("deviceNotActiveException:");
      if (this.deviceNotActiveException == null) {
        sb.append("null");
      } else {
        sb.append(this.deviceNotActiveException);
      }
      first = false;
      if (!first) sb.append(", ");
      sb.append("invalidTemperatureException:");
      if (this.invalidTemperatureException == null) {
        sb.append("null");
      } else {
        sb.append(this.invalidTemperatureException);
      }
      first = false;
      sb.append(")");
      return sb.toString();
    }

    public void validate() throws org.apache.thrift.TException {
      // check for required fields
      // check for sub-struct validity
    }

    private void writeObject(java.io.ObjectOutputStream out) throws java.io.IOException {
      try {
        write(new org.apache.thrift.protocol.TCompactProtocol(new org.apache.thrift.transport.TIOStreamTransport(out)));
      } catch (org.apache.thrift.TException te) {
        throw new java.io.IOException(te);
      }
    }

    private void readObject(java.io.ObjectInputStream in) throws java.io.IOException, java.lang.ClassNotFoundException {
      try {
        // it doesn't seem like you should have to do this, but java serialization is wacky, and doesn't call the default constructor.
        __isset_bitfield = 0;
        read(new org.apache.thrift.protocol.TCompactProtocol(new org.apache.thrift.transport.TIOStreamTransport(in)));
      } catch (org.apache.thrift.TException te) {
        throw new java.io.IOException(te);
      }
    }

    private static class changeTemperature_resultStandardSchemeFactory implements org.apache.thrift.scheme.SchemeFactory {
      public changeTemperature_resultStandardScheme getScheme() {
        return new changeTemperature_resultStandardScheme();
      }
    }

    private static class changeTemperature_resultStandardScheme extends org.apache.thrift.scheme.StandardScheme<changeTemperature_result> {

      public void read(org.apache.thrift.protocol.TProtocol iprot, changeTemperature_result struct) throws org.apache.thrift.TException {
        org.apache.thrift.protocol.TField schemeField;
        iprot.readStructBegin();
        while (true)
        {
          schemeField = iprot.readFieldBegin();
          if (schemeField.type == org.apache.thrift.protocol.TType.STOP) { 
            break;
          }
          switch (schemeField.id) {
            case 0: // SUCCESS
              if (schemeField.type == org.apache.thrift.protocol.TType.DOUBLE) {
                struct.success = iprot.readDouble();
                struct.setSuccessIsSet(true);
              } else { 
                org.apache.thrift.protocol.TProtocolUtil.skip(iprot, schemeField.type);
              }
              break;
            case 1: // DEVICE_NOT_ACTIVE_EXCEPTION
              if (schemeField.type == org.apache.thrift.protocol.TType.STRUCT) {
                struct.deviceNotActiveException = new rpc.thrift.shared.DeviceNotActiveException();
                struct.deviceNotActiveException.read(iprot);
                struct.setDeviceNotActiveExceptionIsSet(true);
              } else { 
                org.apache.thrift.protocol.TProtocolUtil.skip(iprot, schemeField.type);
              }
              break;
            case 2: // INVALID_TEMPERATURE_EXCEPTION
              if (schemeField.type == org.apache.thrift.protocol.TType.STRUCT) {
                struct.invalidTemperatureException = new InvalidTemperatureException();
                struct.invalidTemperatureException.read(iprot);
                struct.setInvalidTemperatureExceptionIsSet(true);
              } else { 
                org.apache.thrift.protocol.TProtocolUtil.skip(iprot, schemeField.type);
              }
              break;
            default:
              org.apache.thrift.protocol.TProtocolUtil.skip(iprot, schemeField.type);
          }
          iprot.readFieldEnd();
        }
        iprot.readStructEnd();

        // check for required fields of primitive type, which can't be checked in the validate method
        struct.validate();
      }

      public void write(org.apache.thrift.protocol.TProtocol oprot, changeTemperature_result struct) throws org.apache.thrift.TException {
        struct.validate();

        oprot.writeStructBegin(STRUCT_DESC);
        if (struct.isSetSuccess()) {
          oprot.writeFieldBegin(SUCCESS_FIELD_DESC);
          oprot.writeDouble(struct.success);
          oprot.writeFieldEnd();
        }
        if (struct.deviceNotActiveException != null) {
          oprot.writeFieldBegin(DEVICE_NOT_ACTIVE_EXCEPTION_FIELD_DESC);
          struct.deviceNotActiveException.write(oprot);
          oprot.writeFieldEnd();
        }
        if (struct.invalidTemperatureException != null) {
          oprot.writeFieldBegin(INVALID_TEMPERATURE_EXCEPTION_FIELD_DESC);
          struct.invalidTemperatureException.write(oprot);
          oprot.writeFieldEnd();
        }
        oprot.writeFieldStop();
        oprot.writeStructEnd();
      }

    }

    private static class changeTemperature_resultTupleSchemeFactory implements org.apache.thrift.scheme.SchemeFactory {
      public changeTemperature_resultTupleScheme getScheme() {
        return new changeTemperature_resultTupleScheme();
      }
    }

    private static class changeTemperature_resultTupleScheme extends org.apache.thrift.scheme.TupleScheme<changeTemperature_result> {

      @Override
      public void write(org.apache.thrift.protocol.TProtocol prot, changeTemperature_result struct) throws org.apache.thrift.TException {
        org.apache.thrift.protocol.TTupleProtocol oprot = (org.apache.thrift.protocol.TTupleProtocol) prot;
        java.util.BitSet optionals = new java.util.BitSet();
        if (struct.isSetSuccess()) {
          optionals.set(0);
        }
        if (struct.isSetDeviceNotActiveException()) {
          optionals.set(1);
        }
        if (struct.isSetInvalidTemperatureException()) {
          optionals.set(2);
        }
        oprot.writeBitSet(optionals, 3);
        if (struct.isSetSuccess()) {
          oprot.writeDouble(struct.success);
        }
        if (struct.isSetDeviceNotActiveException()) {
          struct.deviceNotActiveException.write(oprot);
        }
        if (struct.isSetInvalidTemperatureException()) {
          struct.invalidTemperatureException.write(oprot);
        }
      }

      @Override
      public void read(org.apache.thrift.protocol.TProtocol prot, changeTemperature_result struct) throws org.apache.thrift.TException {
        org.apache.thrift.protocol.TTupleProtocol iprot = (org.apache.thrift.protocol.TTupleProtocol) prot;
        java.util.BitSet incoming = iprot.readBitSet(3);
        if (incoming.get(0)) {
          struct.success = iprot.readDouble();
          struct.setSuccessIsSet(true);
        }
        if (incoming.get(1)) {
          struct.deviceNotActiveException = new rpc.thrift.shared.DeviceNotActiveException();
          struct.deviceNotActiveException.read(iprot);
          struct.setDeviceNotActiveExceptionIsSet(true);
        }
        if (incoming.get(2)) {
          struct.invalidTemperatureException = new InvalidTemperatureException();
          struct.invalidTemperatureException.read(iprot);
          struct.setInvalidTemperatureExceptionIsSet(true);
        }
      }
    }

    private static <S extends org.apache.thrift.scheme.IScheme> S scheme(org.apache.thrift.protocol.TProtocol proto) {
      return (org.apache.thrift.scheme.StandardScheme.class.equals(proto.getScheme()) ? STANDARD_SCHEME_FACTORY : TUPLE_SCHEME_FACTORY).getScheme();
    }
  }

}
