/**
 * Autogenerated by Thrift Compiler (0.12.0)
 *
 * DO NOT EDIT UNLESS YOU ARE SURE THAT YOU KNOW WHAT YOU ARE DOING
 *  @generated
 */
package rpc.thrift.aircondition;


@javax.annotation.Generated(value = "Autogenerated by Thrift Compiler (0.12.0)", date = "2020-04-26")
public enum AirPollution implements org.apache.thrift.TEnum {
  BAD(0),
  NORMAL(1),
  GOOD(2);

  private final int value;

  private AirPollution(int value) {
    this.value = value;
  }

  /**
   * Get the integer value of this enum value, as defined in the Thrift IDL.
   */
  public int getValue() {
    return value;
  }

  /**
   * Find a the enum type by its integer value, as defined in the Thrift IDL.
   * @return null if the value is not found.
   */
  @org.apache.thrift.annotation.Nullable
  public static AirPollution findByValue(int value) { 
    switch (value) {
      case 0:
        return BAD;
      case 1:
        return NORMAL;
      case 2:
        return GOOD;
      default:
        return null;
    }
  }
}
