#
# Autogenerated by Thrift Compiler (0.12.0)
#
# DO NOT EDIT UNLESS YOU ARE SURE THAT YOU KNOW WHAT YOU ARE DOING
#
#  options string: py
#

from thrift.Thrift import TType, TMessageType, TFrozenDict, TException, TApplicationException
from thrift.protocol.TProtocol import TProtocolException
from thrift.TRecursive import fix_spec

import sys
import thrift_python.shared.BaseDevice
import logging
from .ttypes import *
from thrift.Thrift import TProcessor
from thrift.transport import TTransport
all_structs = []


class Iface(thrift_python.shared.BaseDevice.Iface):
    def cleanRooms(self, rooms):
        """
        Parameters:
         - rooms

        """
        pass


class Client(thrift_python.shared.BaseDevice.Client, Iface):
    def __init__(self, iprot, oprot=None):
        thrift_python.shared.BaseDevice.Client.__init__(self, iprot, oprot)

    def cleanRooms(self, rooms):
        """
        Parameters:
         - rooms

        """
        self.send_cleanRooms(rooms)
        return self.recv_cleanRooms()

    def send_cleanRooms(self, rooms):
        self._oprot.writeMessageBegin('cleanRooms', TMessageType.CALL, self._seqid)
        args = cleanRooms_args()
        args.rooms = rooms
        args.write(self._oprot)
        self._oprot.writeMessageEnd()
        self._oprot.trans.flush()

    def recv_cleanRooms(self):
        iprot = self._iprot
        (fname, mtype, rseqid) = iprot.readMessageBegin()
        if mtype == TMessageType.EXCEPTION:
            x = TApplicationException()
            x.read(iprot)
            iprot.readMessageEnd()
            raise x
        result = cleanRooms_result()
        result.read(iprot)
        iprot.readMessageEnd()
        if result.success is not None:
            return result.success
        if result.deviveNotActiveException is not None:
            raise result.deviveNotActiveException
        if result.invalidOrderException is not None:
            raise result.invalidOrderException
        raise TApplicationException(TApplicationException.MISSING_RESULT, "cleanRooms failed: unknown result")


class Processor(thrift_python.shared.BaseDevice.Processor, Iface, TProcessor):
    def __init__(self, handler):
        thrift_python.shared.BaseDevice.Processor.__init__(self, handler)
        self._processMap["cleanRooms"] = Processor.process_cleanRooms

    def process(self, iprot, oprot):
        (name, type, seqid) = iprot.readMessageBegin()
        if name not in self._processMap:
            iprot.skip(TType.STRUCT)
            iprot.readMessageEnd()
            x = TApplicationException(TApplicationException.UNKNOWN_METHOD, 'Unknown function %s' % (name))
            oprot.writeMessageBegin(name, TMessageType.EXCEPTION, seqid)
            x.write(oprot)
            oprot.writeMessageEnd()
            oprot.trans.flush()
            return
        else:
            self._processMap[name](self, seqid, iprot, oprot)
        return True

    def process_cleanRooms(self, seqid, iprot, oprot):
        args = cleanRooms_args()
        args.read(iprot)
        iprot.readMessageEnd()
        result = cleanRooms_result()
        try:
            result.success = self._handler.cleanRooms(args.rooms)
            msg_type = TMessageType.REPLY
        except TTransport.TTransportException:
            raise
        except thrift_python.shared.ttypes.DeviceNotActiveException as deviveNotActiveException:
            msg_type = TMessageType.REPLY
            result.deviveNotActiveException = deviveNotActiveException
        except InvalidOrderException as invalidOrderException:
            msg_type = TMessageType.REPLY
            result.invalidOrderException = invalidOrderException
        except TApplicationException as ex:
            logging.exception('TApplication exception in handler')
            msg_type = TMessageType.EXCEPTION
            result = ex
        except Exception:
            logging.exception('Unexpected exception in handler')
            msg_type = TMessageType.EXCEPTION
            result = TApplicationException(TApplicationException.INTERNAL_ERROR, 'Internal error')
        oprot.writeMessageBegin("cleanRooms", msg_type, seqid)
        result.write(oprot)
        oprot.writeMessageEnd()
        oprot.trans.flush()

# HELPER FUNCTIONS AND STRUCTURES


class cleanRooms_args(object):
    """
    Attributes:
     - rooms

    """


    def __init__(self, rooms=None,):
        self.rooms = rooms

    def read(self, iprot):
        if iprot._fast_decode is not None and isinstance(iprot.trans, TTransport.CReadableTransport) and self.thrift_spec is not None:
            iprot._fast_decode(self, iprot, [self.__class__, self.thrift_spec])
            return
        iprot.readStructBegin()
        while True:
            (fname, ftype, fid) = iprot.readFieldBegin()
            if ftype == TType.STOP:
                break
            if fid == 1:
                if ftype == TType.SET:
                    self.rooms = set()
                    (_etype10, _size7) = iprot.readSetBegin()
                    for _i11 in range(_size7):
                        _elem12 = iprot.readI32()
                        self.rooms.add(_elem12)
                    iprot.readSetEnd()
                else:
                    iprot.skip(ftype)
            else:
                iprot.skip(ftype)
            iprot.readFieldEnd()
        iprot.readStructEnd()

    def write(self, oprot):
        if oprot._fast_encode is not None and self.thrift_spec is not None:
            oprot.trans.write(oprot._fast_encode(self, [self.__class__, self.thrift_spec]))
            return
        oprot.writeStructBegin('cleanRooms_args')
        if self.rooms is not None:
            oprot.writeFieldBegin('rooms', TType.SET, 1)
            oprot.writeSetBegin(TType.I32, len(self.rooms))
            for iter13 in self.rooms:
                oprot.writeI32(iter13)
            oprot.writeSetEnd()
            oprot.writeFieldEnd()
        oprot.writeFieldStop()
        oprot.writeStructEnd()

    def validate(self):
        return

    def __repr__(self):
        L = ['%s=%r' % (key, value)
             for key, value in self.__dict__.items()]
        return '%s(%s)' % (self.__class__.__name__, ', '.join(L))

    def __eq__(self, other):
        return isinstance(other, self.__class__) and self.__dict__ == other.__dict__

    def __ne__(self, other):
        return not (self == other)
all_structs.append(cleanRooms_args)
cleanRooms_args.thrift_spec = (
    None,  # 0
    (1, TType.SET, 'rooms', (TType.I32, None, False), None, ),  # 1
)


class cleanRooms_result(object):
    """
    Attributes:
     - success
     - deviveNotActiveException
     - invalidOrderException

    """


    def __init__(self, success=None, deviveNotActiveException=None, invalidOrderException=None,):
        self.success = success
        self.deviveNotActiveException = deviveNotActiveException
        self.invalidOrderException = invalidOrderException

    def read(self, iprot):
        if iprot._fast_decode is not None and isinstance(iprot.trans, TTransport.CReadableTransport) and self.thrift_spec is not None:
            iprot._fast_decode(self, iprot, [self.__class__, self.thrift_spec])
            return
        iprot.readStructBegin()
        while True:
            (fname, ftype, fid) = iprot.readFieldBegin()
            if ftype == TType.STOP:
                break
            if fid == 0:
                if ftype == TType.SET:
                    self.success = set()
                    (_etype17, _size14) = iprot.readSetBegin()
                    for _i18 in range(_size14):
                        _elem19 = iprot.readI32()
                        self.success.add(_elem19)
                    iprot.readSetEnd()
                else:
                    iprot.skip(ftype)
            elif fid == 1:
                if ftype == TType.STRUCT:
                    self.deviveNotActiveException = thrift_python.shared.ttypes.DeviceNotActiveException()
                    self.deviveNotActiveException.read(iprot)
                else:
                    iprot.skip(ftype)
            elif fid == 2:
                if ftype == TType.STRUCT:
                    self.invalidOrderException = InvalidOrderException()
                    self.invalidOrderException.read(iprot)
                else:
                    iprot.skip(ftype)
            else:
                iprot.skip(ftype)
            iprot.readFieldEnd()
        iprot.readStructEnd()

    def write(self, oprot):
        if oprot._fast_encode is not None and self.thrift_spec is not None:
            oprot.trans.write(oprot._fast_encode(self, [self.__class__, self.thrift_spec]))
            return
        oprot.writeStructBegin('cleanRooms_result')
        if self.success is not None:
            oprot.writeFieldBegin('success', TType.SET, 0)
            oprot.writeSetBegin(TType.I32, len(self.success))
            for iter20 in self.success:
                oprot.writeI32(iter20)
            oprot.writeSetEnd()
            oprot.writeFieldEnd()
        if self.deviveNotActiveException is not None:
            oprot.writeFieldBegin('deviveNotActiveException', TType.STRUCT, 1)
            self.deviveNotActiveException.write(oprot)
            oprot.writeFieldEnd()
        if self.invalidOrderException is not None:
            oprot.writeFieldBegin('invalidOrderException', TType.STRUCT, 2)
            self.invalidOrderException.write(oprot)
            oprot.writeFieldEnd()
        oprot.writeFieldStop()
        oprot.writeStructEnd()

    def validate(self):
        return

    def __repr__(self):
        L = ['%s=%r' % (key, value)
             for key, value in self.__dict__.items()]
        return '%s(%s)' % (self.__class__.__name__, ', '.join(L))

    def __eq__(self, other):
        return isinstance(other, self.__class__) and self.__dict__ == other.__dict__

    def __ne__(self, other):
        return not (self == other)
all_structs.append(cleanRooms_result)
cleanRooms_result.thrift_spec = (
    (0, TType.SET, 'success', (TType.I32, None, False), None, ),  # 0
    (1, TType.STRUCT, 'deviveNotActiveException', [thrift_python.shared.ttypes.DeviceNotActiveException, None], None, ),  # 1
    (2, TType.STRUCT, 'invalidOrderException', [InvalidOrderException, None], None, ),  # 2
)
fix_spec(all_structs)
del all_structs

