# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: cv.proto

from google.protobuf.internal import enum_type_wrapper
from google.protobuf import descriptor as _descriptor
from google.protobuf import message as _message
from google.protobuf import reflection as _reflection
from google.protobuf import symbol_database as _symbol_database
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor.FileDescriptor(
  name='cv.proto',
  package='',
  syntax='proto3',
  serialized_options=b'\n\rio.grpc.protoB\007CVProtoP\001',
  serialized_pb=b'\n\x08\x63v.proto\"d\n\x07Request\x12\x1f\n\x06\x61\x63tion\x18\x01 \x01(\x0e\x32\x0f.Request.Action\x12\x19\n\x07\x63ountry\x18\x02 \x01(\x0e\x32\x08.Country\"\x1d\n\x06\x41\x63tion\x12\t\n\x05START\x10\x00\x12\x08\n\x04STOP\x10\x01\"[\n\x0f\x43urriculumVitae\x12\x17\n\x06person\x18\x01 \x01(\x0b\x32\x07.Person\x12\x1a\n\x0cpreviousJobs\x18\x02 \x03(\x0b\x32\x04.Job\x12\x13\n\x0b\x64\x65scription\x18\x03 \x01(\t\"#\n\x03Job\x12\x0b\n\x03job\x18\x01 \x01(\t\x12\x0f\n\x07\x63ompany\x18\x02 \x01(\t\"j\n\x06Person\x12\x11\n\tfirstName\x18\x01 \x01(\t\x12\x12\n\nsecondName\x18\x02 \x01(\t\x12\x15\n\x05\x62irth\x18\x03 \x01(\x0b\x32\x06.Birth\x12\r\n\x05\x65mail\x18\x04 \x01(\t\x12\x13\n\x0bphoneNumber\x18\x05 \x01(\t\"0\n\x05\x42irth\x12\x19\n\x07\x63ountry\x18\x01 \x01(\x0e\x32\x08.Country\x12\x0c\n\x04\x64\x61te\x18\x02 \x01(\t*A\n\x07\x43ountry\x12\x06\n\x02US\x10\x00\x12\n\n\x06Poland\x10\x01\x12\x0b\n\x07Germany\x10\x02\x12\n\n\x06\x46rance\x10\x03\x12\t\n\x05Japan\x10\x04\x32\x34\n\x02\x43V\x12.\n\x0cSubscription\x12\x08.Request\x1a\x10.CurriculumVitae(\x01\x30\x01\x42\x1a\n\rio.grpc.protoB\x07\x43VProtoP\x01\x62\x06proto3'
)

_COUNTRY = _descriptor.EnumDescriptor(
  name='Country',
  full_name='Country',
  filename=None,
  file=DESCRIPTOR,
  values=[
    _descriptor.EnumValueDescriptor(
      name='US', index=0, number=0,
      serialized_options=None,
      type=None),
    _descriptor.EnumValueDescriptor(
      name='Poland', index=1, number=1,
      serialized_options=None,
      type=None),
    _descriptor.EnumValueDescriptor(
      name='Germany', index=2, number=2,
      serialized_options=None,
      type=None),
    _descriptor.EnumValueDescriptor(
      name='France', index=3, number=3,
      serialized_options=None,
      type=None),
    _descriptor.EnumValueDescriptor(
      name='Japan', index=4, number=4,
      serialized_options=None,
      type=None),
  ],
  containing_type=None,
  serialized_options=None,
  serialized_start=402,
  serialized_end=467,
)
_sym_db.RegisterEnumDescriptor(_COUNTRY)

Country = enum_type_wrapper.EnumTypeWrapper(_COUNTRY)
US = 0
Poland = 1
Germany = 2
France = 3
Japan = 4


_REQUEST_ACTION = _descriptor.EnumDescriptor(
  name='Action',
  full_name='Request.Action',
  filename=None,
  file=DESCRIPTOR,
  values=[
    _descriptor.EnumValueDescriptor(
      name='START', index=0, number=0,
      serialized_options=None,
      type=None),
    _descriptor.EnumValueDescriptor(
      name='STOP', index=1, number=1,
      serialized_options=None,
      type=None),
  ],
  containing_type=None,
  serialized_options=None,
  serialized_start=83,
  serialized_end=112,
)
_sym_db.RegisterEnumDescriptor(_REQUEST_ACTION)


_REQUEST = _descriptor.Descriptor(
  name='Request',
  full_name='Request',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='action', full_name='Request.action', index=0,
      number=1, type=14, cpp_type=8, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='country', full_name='Request.country', index=1,
      number=2, type=14, cpp_type=8, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
    _REQUEST_ACTION,
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=12,
  serialized_end=112,
)


_CURRICULUMVITAE = _descriptor.Descriptor(
  name='CurriculumVitae',
  full_name='CurriculumVitae',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='person', full_name='CurriculumVitae.person', index=0,
      number=1, type=11, cpp_type=10, label=1,
      has_default_value=False, default_value=None,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='previousJobs', full_name='CurriculumVitae.previousJobs', index=1,
      number=2, type=11, cpp_type=10, label=3,
      has_default_value=False, default_value=[],
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='description', full_name='CurriculumVitae.description', index=2,
      number=3, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=b"".decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=114,
  serialized_end=205,
)


_JOB = _descriptor.Descriptor(
  name='Job',
  full_name='Job',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='job', full_name='Job.job', index=0,
      number=1, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=b"".decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='company', full_name='Job.company', index=1,
      number=2, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=b"".decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=207,
  serialized_end=242,
)


_PERSON = _descriptor.Descriptor(
  name='Person',
  full_name='Person',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='firstName', full_name='Person.firstName', index=0,
      number=1, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=b"".decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='secondName', full_name='Person.secondName', index=1,
      number=2, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=b"".decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='birth', full_name='Person.birth', index=2,
      number=3, type=11, cpp_type=10, label=1,
      has_default_value=False, default_value=None,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='email', full_name='Person.email', index=3,
      number=4, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=b"".decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='phoneNumber', full_name='Person.phoneNumber', index=4,
      number=5, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=b"".decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=244,
  serialized_end=350,
)


_BIRTH = _descriptor.Descriptor(
  name='Birth',
  full_name='Birth',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='country', full_name='Birth.country', index=0,
      number=1, type=14, cpp_type=8, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='date', full_name='Birth.date', index=1,
      number=2, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=b"".decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=352,
  serialized_end=400,
)

_REQUEST.fields_by_name['action'].enum_type = _REQUEST_ACTION
_REQUEST.fields_by_name['country'].enum_type = _COUNTRY
_REQUEST_ACTION.containing_type = _REQUEST
_CURRICULUMVITAE.fields_by_name['person'].message_type = _PERSON
_CURRICULUMVITAE.fields_by_name['previousJobs'].message_type = _JOB
_PERSON.fields_by_name['birth'].message_type = _BIRTH
_BIRTH.fields_by_name['country'].enum_type = _COUNTRY
DESCRIPTOR.message_types_by_name['Request'] = _REQUEST
DESCRIPTOR.message_types_by_name['CurriculumVitae'] = _CURRICULUMVITAE
DESCRIPTOR.message_types_by_name['Job'] = _JOB
DESCRIPTOR.message_types_by_name['Person'] = _PERSON
DESCRIPTOR.message_types_by_name['Birth'] = _BIRTH
DESCRIPTOR.enum_types_by_name['Country'] = _COUNTRY
_sym_db.RegisterFileDescriptor(DESCRIPTOR)

Request = _reflection.GeneratedProtocolMessageType('Request', (_message.Message,), {
  'DESCRIPTOR' : _REQUEST,
  '__module__' : 'cv_pb2'
  # @@protoc_insertion_point(class_scope:Request)
  })
_sym_db.RegisterMessage(Request)

CurriculumVitae = _reflection.GeneratedProtocolMessageType('CurriculumVitae', (_message.Message,), {
  'DESCRIPTOR' : _CURRICULUMVITAE,
  '__module__' : 'cv_pb2'
  # @@protoc_insertion_point(class_scope:CurriculumVitae)
  })
_sym_db.RegisterMessage(CurriculumVitae)

Job = _reflection.GeneratedProtocolMessageType('Job', (_message.Message,), {
  'DESCRIPTOR' : _JOB,
  '__module__' : 'cv_pb2'
  # @@protoc_insertion_point(class_scope:Job)
  })
_sym_db.RegisterMessage(Job)

Person = _reflection.GeneratedProtocolMessageType('Person', (_message.Message,), {
  'DESCRIPTOR' : _PERSON,
  '__module__' : 'cv_pb2'
  # @@protoc_insertion_point(class_scope:Person)
  })
_sym_db.RegisterMessage(Person)

Birth = _reflection.GeneratedProtocolMessageType('Birth', (_message.Message,), {
  'DESCRIPTOR' : _BIRTH,
  '__module__' : 'cv_pb2'
  # @@protoc_insertion_point(class_scope:Birth)
  })
_sym_db.RegisterMessage(Birth)


DESCRIPTOR._options = None

_CV = _descriptor.ServiceDescriptor(
  name='CV',
  full_name='CV',
  file=DESCRIPTOR,
  index=0,
  serialized_options=None,
  serialized_start=469,
  serialized_end=521,
  methods=[
  _descriptor.MethodDescriptor(
    name='Subscription',
    full_name='CV.Subscription',
    index=0,
    containing_service=None,
    input_type=_REQUEST,
    output_type=_CURRICULUMVITAE,
    serialized_options=None,
  ),
])
_sym_db.RegisterServiceDescriptor(_CV)

DESCRIPTOR.services_by_name['CV'] = _CV

# @@protoc_insertion_point(module_scope)
